### ISSUE TITLE
How to do event handling for android and iOS in react native's new architecture for fabric components?

### ISSUE THREAD

**Issue by BraveEvidence** [Elabar/react-native-fancy-signature#1]
Sorry to open this as an issue but can you please help me with https://stackoverflow.com/questions/72981626/how-to-do-event-handling-for-android-and-ios-in-react-natives-new-architecture

Thanks

**Comment by Elabar** [comment]
I also stumbled upon this (similar) during the making of this module, and I do not have time to continue exploring it at the moment. 

Will try to figure this out by the end of this week. Also, you can join [this group](https://github.com/reactwg/react-native-new-architecture) and ask around. There are some practical but not well documented materials regarding the new architecture in it.

**Comment by BraveEvidence** [comment]
Thanks. Let me know in case you figured it out. I have tried joining [this group](https://github.com/reactwg/react-native-new-architecture) but was not accepted
